---
- name: Download Dynatrace OneAgent installer
  win_get_url:
    url: "{{ _oneagent_installer_url }}"
    dest: "{{ oneagent_installer_path }}"
    validate_certs:
      "{{ oneagent_internal_validate_certs | default(true) | bool }}"
    headers:
      Authorization: Api-Token {{ oneagent_paas_token }}
  no_log: true
  ignore_errors: true
  register: _oneagent_download_result
